### ISSUE TITLE
Adding a task to set the hash part only

### ISSUE THREAD

**Issue by ondras** [elm-community/elm-history#12]
This module seems to be missing an API for hash modification, similar to what "location.hash = ..." does.

The only way right now is to use `setPath "#stuff"`, but this is quite problematic and semantically different:
1. there is no way to _remove_ the hash,
2. duplicate `location.hash = x` are ignored and do not increase the history stack size, while duplicate `history.pushState` calls (i.e. `setPath`) grow the history uselessly.

**Comment by lukewestby** [comment]
Agreed. Do you want to submit a PR?

**Comment by ondras** [comment]
I am a complete Elm newbie, so there is a reasonable chance that I will fail miserably. But yeah anyway, I will try to have something done.

**Comment by ondras** [comment]
@lukewestby created a basic PR :smile:

**Comment by rgrempel** [comment]
Thanks!

I've merged your PR, and published it in version 1.2.0.
