### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by sporto** [elm-community/elm-history#13]
This module needs some good integration tests, I recently added some to my library (hop) with the following setup:
- Integration test are written in Elixir hound https://hexdocs.pm/hound/readme.html
- Test run inside docker using docker-compose
- Docker compose launches an example elm app in a browser
- Also launches a webdriver in a container
- And the integration test in hound in another container
- All these runs in Semaphore CI https://semaphoreci.com/

I think is important to have this library well tested as is an important building block. So I offer my self to replicate this setup and write some tests if you like it.

Thanks

**Comment by rgrempel** [comment]
That would be wonderful!

I'm not familiar with Elixir, but having taken a quick look at it, I would like to be! It certainly looks like more fun than writing Webdriver automation in Javascript.

And semaphoreci looks interesting as well -- I'm more familiar with Travis, but would be interested in seeing how semaphoreci compares.

So, I would encourage you to go for it -- I'll happily merge changes, or just give you "collaborator" rights.

**Comment by lukewestby** [comment]
@sporto would this be easier for you to do if you were an elm-community member? @rgrempel or one of the other owners would need to make that change but i don't see any reason why not

**Comment by sporto** [comment]
Yes it would be easier if you give me collaborator access so I can set up the ci integration myself

Thanks

**Comment by lukewestby** [comment]
@sporto I added you as a collaborator just now!

**Comment by sporto** [comment]
Thanks

**Comment by sporto** [comment]
I have create a branch for this https://github.com/elm-community/elm-history/tree/integration-tests

I cannot set up Semaphore CI with my current access, I think I need to be an organisation member or maybe someone else can set this up.

**Comment by rgrempel** [comment]
I've set up an organization account for elm-community at Semaphore CI, and I think I've made you an admin there, @sporto. Take a look and see if I've done that correctly!

**Comment by sporto** [comment]
@rgrempel   @lukewestby     PR ready for review https://github.com/elm-community/elm-history/pull/16

**Comment by rgrempel** [comment]
Merged ... thanks again for doing this!
