### ISSUE TITLE
Updating for Elm 0.17

### ISSUE THREAD

**Issue by rgrempel** [elm-community/elm-history#17]
elm-history would need a substantial rewrite in order to work with Elm 0.17.

However, it appears that @elm-lang is planning to publish a History module that works with 0.17. Furthermore, it has been stated that the policy of @elm-lang will be that modules wrapping Web APIs should be owned by @elm-lang.

So, I guess the question is whether to go ahead and update elm-history for 0.17 or not. Personally, I am not eager to do it, given the considerations mentioned above. However, I suppose my opinion might change if no History module is forthcoming from @elm-lang.

**Comment by eeue56** [comment]
This should be moved to elm-lang, yes. I can take a look at updating it for 0.17 if Evan doesn't get around to it soon.

**Comment by sporto** [comment]
I'll be happy to upgrade and mantain this lib as it is critical for me. Ping me if it needs a mantainer.

**Comment by rgrempel** [comment]
I was thinking a little more about the mechanism for updating this for Elm 0.17.

I believe that the following things are all true -- but it's possible that I've got something wrong.
- The things this module does would need to be done via subscriptions in Elm 0.17.
- The only way to create subscriptions is to be an `effects` module.
- It appears that effects modules cannot be published unless whitelisted. (I don't think there has been an official statement about this, but @mgold reports trying to publish an effects module and not succeeding. And, there is an effects-whitelist file in the elm-package repository).
- Thus, the fact that this module is in the "native whitelist" won't be sufficient.

So, I think the ball is in @elm-lang's court -- it will need to either publish a similar module, or put this on the effects whitelist.

Of course, it's possible that some element of my analysis is flawed.

**Comment by eeue56** [comment]
@rgrempel I am pairing with upgrading this with Evan tomorrow.

**Comment by sporto** [comment]
@eeue56     that is excellent news!

As a router author what would be really great things to have are:
- A subscription for location (as a string or record) equivalent to `href` in 0.16 version
- A way to pushState, eq to setPath
- A way to retrieve the current location on demand as per `location` in 0.16 version

It would be better if both the subscription and the get location task return the same thing

**Comment by mgold** [comment]
+1 for elm-lang taking this over, as it is part of the "web platform".

**Comment by eeue56** [comment]
News coming soon.

**Comment by rgrempel** [comment]
Now that elm-lang/navigation has been published, I think the only "gaps" which could be filled here are:
- The tasks provided in https://github.com/elm-community/elm-history/blob/master/src/Location.elm
  - A task to get the `Location`
  - Tasks to reload the current page, or actually fetch a different URL
- The `setHash` and `length` tasks from https://github.com/elm-community/elm-history/blob/master/src/History.elm

These could be filled here because they don't require an "effects" module.

So, the questions are:
- are any of these essential?
- given elm-lang's policy that elm-lang will provide whatever access to web APIs is right and proper, should we be in the business of filling "gaps" of this kind?

**Comment by mgold** [comment]
My current opinion is that this module is superseded by elm-lang/navigation. It makes a lot of sense to have an official and low-level way of accessing the web platform. It makes sense for anyone who has an opinion on a useful abstraction on top of that to publish a personal library. But there doesn't currently seem to be an "objective" or "neutral" way to build, usefully, on the official package.

**Comment by jvoigtlaender** [comment]
What's the state of this? It wasn't updated for 0.17, and 0.18 is already on the horizon. So is this repository officially deprecated now? And can this issue (and the other issue and PR) consequently be closed for good?

**Comment by eeue56** [comment]
This repo is dead, yep
