### ISSUE TITLE
Publish to Elm Packages (?) 

### ISSUE THREAD

**Issue by lseppala** [elm-community/elm-history#2]
I'm glad to see this effort to adopt popular Elm libraries that haven't been updated by the original author! Very much a needed effort :)

This forked and updated package hasn't been published to [package.elm-lang.org]() yet. Is there a particular reason why? I know anyone clone this repo and publish the package, but I want to make sure this isn't against the charter or something.

**Comment by jvoigtlaender** [comment]
Actually, nobody will be able to simply clone this repo and publish the package. It contains native code, so before it can be published to the official site, @evancz would have to accept the following pull request: https://github.com/elm-lang/package.elm-lang.org/pull/124.

**Comment by lseppala** [comment]
Ah! I didn't know that packages with native code had to be whitelisted. Apologies, I didn't know this process was already in the pipe. Thanks, and closing out.
