### ISSUE TITLE
Any updates for elm 0.18?

### ISSUE THREAD

**Issue by ChrisZou** [elm-community/elm-history#20]
Any updates on this package? Elm 0.18 is here and it seems compatible version for elm 0.17 is not in the master branch yet.

**Comment by eeue56** [comment]
Use elm-lang/navigation instead. This package is deprecated and will not be published.

**Comment by zoul** [comment]
Pardon me for ressurecting this issue – if I want a replacement for `Location.assign` offered by this module, how would I do it using the Navigation module?

**Comment by eeue56** [comment]
@zoul you'd be better off asking on the elm-slack
