### ISSUE TITLE
A Signal for the entire Location

### ISSUE THREAD

**Issue by rgrempel** [elm-community/elm-history#4]
At the moment, elm-history offers signals for the `location.path` and `location.hash`. However, people are sometimes interested in other parts of the location -- say, for instance, the query string.

In fact, there is a pull request open elsewhere to add this: https://github.com/TheSeamau5/elm-history/pull/5

Now, what I would propose to do instead is create a `Signal Location`, where the `Location` is a record that has _all_ the parts of the location object. That way, people can just pick out the parts they want. (In fact, a signal of just hashes, for instance, would just be a `Signal.map` of the `Signal Location`).

So, I'd propose to go ahead and do that, but I'll wait a few days to see if anyone has any comments.

**Comment by Apanatshka** [comment]
Sounds good. I do think we need to have helper functions for extracting interesting parts from the `Location`, so you can easily `Signal.map` stuff.

**Comment by rgrempel** [comment]
Just to give an update on this, I've been working on integrating some tests -- both elm-test type tests and selenium tests via SauceLabs etc., since we're in a space here where cross-browser differences can matter a bit.

Once that's ready, I can do the `Task x Location` and `Signal Location` stuff fairly quickly, I think.

But, we're going somewhere sunny (and without Internet) for Christmas, so I won't get this done until about the end of December.

So, just wanted to say where I'm at on this -- I don't mean to block anything if someone wants to take a run at this before then.

**Comment by jur0** [comment]
@rgrempel have you done anything about this lately?
