### ISSUE TITLE
`setPath` pushes new entry to History if the URL is the same as the current one.

### ISSUE THREAD

**Issue by gdotdesign** [elm-community/elm-history#6]

**Comment by elliotdickison** [comment]
@gdotdesign This is the correct behavior according to the [history API spec](https://html.spec.whatwg.org/multipage/browsers.html#the-history-interface:dom-history-pushstate-3). The behavior you describe holds true when changing just the hash (not with the history API), could that be what you're thinking of?

**Comment by gdotdesign** [comment]
Yeah, didn't realize that `pushState` works this way, never mind then.
